[pytest]
log_cli = true
log_cli_level = INFO

markers=
    smoke
    regression:
    user:User related test cases
    product:Product related test cases
    #customer:

addopts = -v -s

python_files = test_*.py
python_classes = Test*
python_functions = test_*

